# Generated by Django 5.1.2 on 2024-10-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_remove_userprofile_balance_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('-', '-'), ('person', 'Person'), ('legal_entity', 'Legal Entity')], max_length=20, null=True),
        ),
    ]
