# Generated by Django 5.1.2 on 2024-10-22 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_userprofile_password_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cnpj',
            field=models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('person', 'Person'), ('legal_entity', 'Legal Entity')], max_length=20, null=True),
        ),
    ]
